name: 'Deploy'

on:
  push:
    branches:
      - main
        #pull_request:
        #  branches:
        #    - main
        #  types: [closed]

jobs:
  validation:
    name: Validate Code
    uses: ./.github/workflows/validate-wf.yml
    permissions:
      checks: write
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Repo Name
        id: repo_name
        run: | 
          echo "repo_name=$(echo '${{ github.repository }}' | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
          echo ${{ steps.repo_name.outputs.repo_name }}
          
      - name: Rename 'src' to Module Name
        shell: pwsh
        run: |
          Rename-Item -Path ./src/ -NewName ${{ steps.repo_name.outputs.repo_name }} -Force
          
      - name: Publish PowerShell
        uses: natescherer/publish-powershell-action@v1.0.3
        with:
          token: ${{ secrets.PSGalleryToken }}
          target: gallery
          path: ${{ steps.repo_name.outputs.repo_name }}/
