name: Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, review_requested]
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:
    
jobs:
  validation:
    name: Validate Code
    uses: ./.github/workflows/validate-wf.yml
    permissions:
      checks: write
